// vocabulary.js

// Geniş Türkçe Yanlış Şıklar Havuzu
const TURKISH_OPTIONS_POOL = [
    "hızlı", "yavaş", "büyük", "küçük", "gelmek", "gitmek", 
    "yemek", "içmek", "ev", "araba", "güneş", "ay", "kitap", 
    "kalem", "masa", "sandalye", "su", "hava", "toprak", "ateş", 
    "yürümek", "koşmak", "uyumak", "konuşmak", "yazmak", "okumak",
    "sessiz", "gürültülü", "mutlu", "üzgün", "iyi", "kötü",
    "zengin", "fakir", "eski", "yeni", "siyah", "beyaz", "mavi",
    "kırmızı", "yeşil", "sarı", "zor", "kolay", "başlamak", 
    "bitirmek", "düşünmek", "hissetmek", "görmek", "duymak",
    "bulmak", "kaybetmek", "ağaç", "çiçek", "dağ", "deniz", 
    "nehir", "göl", "şehir", "köy", "sokak", "cadde", "bina",
    "kapı", "pencere", "saat", "dakika", "saniye", "hafta",
    "ay", "yıl", "dün", "bugün", "yarın", "sabah", "öğle", "akşam",
    "bilgisayar", "telefon", "kulaklık", "şarkı", "dans etmek", "gülmek",
    "ağlamak", "öğretmen", "öğrenci", "doktor", "polis", "banka",
    "para", "alışveriş", "pazar", "yemekhane", "mutfak", "banyo", 
    "tuvalet", "yatak odası", "oturma odası", "kış", "ilkbahar", 
    "yaz", "sonbahar", "sıcak", "soğuk", "rüzgar", "yağmur", 
    "kar", "gökyüzü", "yıldız", "gezegen", "uzay", "robot",
    "makine", "fabrika", "çalışan", "patron", "toplantı", "rapor", 
    "sunum", "tatlı", "acı", "ekşi", "tuzlu", "şeker", "bal", 
    "ekmek", "peynir", "zeytin", "yumurta", "süt", "kahve", 
    "çay", "meyve", "sebze", "elma", "armut", "muz", "portakal"
];

// Kelime listesi: Her seviyeden tam 100 kelime. Toplam 600 kelime.
const VOCABULARY = {
    A1: [
        { word: "Hello", translation: "Merhaba" },
        { word: "Bye", translation: "Güle güle" },
        { word: "Yes", translation: "Evet" },
        { word: "No", translation: "Hayır" },
        { word: "Please", translation: "Lütfen" },
        { word: "Thank you", translation: "Teşekkürler" },
        { word: "Dog", translation: "Köpek" },
        { word: "Cat", translation: "Kedi" },
        { word: "House", translation: "Ev" },
        { word: "Car", translation: "Araba" },
        { word: "Book", translation: "Kitap" },
        { word: "Water", translation: "Su" },
        { word: "Food", translation: "Yiyecek" },
        { word: "Eat", translation: "Yemek yemek" },
        { word: "Drink", translation: "İçmek" },
        { word: "Go", translation: "Gitmek" },
        { word: "Come", translation: "Gelmek" },
        { word: "Walk", translation: "Yürümek" },
        { word: "Run", translation: "Koşmak" },
        { word: "Sleep", translation: "Uyumak" },
        { word: "Bed", translation: "Yatak" },
        { word: "Table", translation: "Masa" },
        { word: "Chair", translation: "Sandalye" },
        { word: "Bag", translation: "Çanta" },
        { word: "Pen", translation: "Tükenmez kalem" },
        { word: "Pencil", translation: "Kurşun kalem" },
        { word: "Big", translation: "Büyük" },
        { word: "Small", translation: "Küçük" },
        { word: "Old", translation: "Yaşlı/Eski" },
        { word: "New", translation: "Yeni" },
        { word: "Good", translation: "İyi" },
        { word: "Bad", translation: "Kötü" },
        { word: "Happy", translation: "Mutlu" },
        { word: "Sad", translation: "Üzgün" },
        { word: "Day", translation: "Gün" },
        { word: "Night", translation: "Gece" },
        { word: "Sun", translation: "Güneş" },
        { word: "Moon", translation: "Ay" },
        { word: "Star", translation: "Yıldız" },
        { word: "Cold", translation: "Soğuk" },
        { word: "Hot", translation: "Sıcak" },
        { word: "Tree", translation: "Ağaç" },
        { word: "Flower", translation: "Çiçek" },
        { word: "Open", translation: "Açık/Açmak" },
        { word: "Close", translation: "Kapalı/Kapatmak" },
        { word: "Look", translation: "Bakmak" },
        { word: "See", translation: "Görmek" },
        { word: "Listen", translation: "Dinlemek" },
        { word: "Hear", translation: "Duymak" },
        { word: "Time", translation: "Zaman" },
        { word: "Now", translation: "Şimdi" },
        { word: "Later", translation: "Sonra" },
        { word: "Mother", translation: "Anne" },
        { word: "Father", translation: "Baba" },
        { word: "Brother", translation: "Erkek kardeş" },
        { word: "Sister", translation: "Kız kardeş" },
        { word: "Family", translation: "Aile" },
        { word: "Friend", translation: "Arkadaş" },
        { word: "Play", translation: "Oynamak" },
        { word: "Work", translation: "Çalışmak" },
        { word: "School", translation: "Okul" },
        { word: "Teacher", translation: "Öğretmen" },
        { word: "Student", translation: "Öğrenci" },
        { word: "Money", translation: "Para" },
        { word: "Buy", translation: "Satın almak" },
        { word: "Sell", translation: "Satmak" },
        { word: "Shop", translation: "Dükkan" },
        { word: "Street", translation: "Sokak" },
        { word: "City", translation: "Şehir" },
        { word: "Country", translation: "Ülke" },
        { word: "Color", translation: "Renk" },
        { word: "Red", translation: "Kırmızı" },
        { word: "Blue", translation: "Mavi" },
        { word: "Green", translation: "Yeşil" },
        { word: "Yellow", translation: "Sarı" },
        { word: "Black", translation: "Siyah" },
        { word: "White", translation: "Beyaz" },
        { word: "Brown", translation: "Kahverengi" },
        { word: "Minute", translation: "Dakika" },
        { word: "Hour", translation: "Saat (zaman)" },
        { word: "Week", translation: "Hafta" },
        { word: "Month", translation: "Ay" },
        { word: "Year", translation: "Yıl" },
        { word: "Today", translation: "Bugün" },
        { word: "Yesterday", translation: "Dün" },
        { word: "Tomorrow", translation: "Yarın" },
        { word: "Morning", translation: "Sabah" },
        { word: "Evening", translation: "Akşam" },
        { word: "Hello", translation: "Selam" },
        { word: "Excuse me", translation: "Affedersiniz" },
        { word: "Sorry", translation: "Üzgünüm" },
        { word: "Speak", translation: "Konuşmak" },
        { word: "Write", translation: "Yazmak" },
        { word: "Read", translation: "Okumak" },
        { word: "Find", translation: "Bulmak" },
        { word: "Lost", translation: "Kayıp" },
        { word: "Door", translation: "Kapı" },
        { word: "Window", translation: "Pencere" }
    ],
    A2: [
        { word: "Often", translation: "Sık sık" },
        { word: "Ready", translation: "Hazır" },
        { word: "Suddenly", translation: "Aniden" },
        { word: "Travel", translation: "Seyahat etmek" },
        { word: "Holiday", translation: "Tatil" },
        { word: "Weather", translation: "Hava durumu" },
        { word: "Future", translation: "Gelecek" },
        { word: "Present", translation: "Şimdiki zaman" },
        { word: "Difference", translation: "Fark" },
        { word: "Enjoy", translation: "Keyif almak" },
        { word: "Usually", translation: "Genellikle" },
        { word: "Always", translation: "Her zaman" },
        { word: "Never", translation: "Asla" },
        { word: "Sometimes", translation: "Bazen" },
        { word: "Important", translation: "Önemli" },
        { word: "Easy", translation: "Kolay" },
        { word: "Difficult", translation: "Zor" },
        { word: "Together", translation: "Birlikte" },
        { word: "Alone", translation: "Yalnız" },
        { word: "Because", translation: "Çünkü" },
        { word: "Although", translation: "Rağmen" },
        { word: "During", translation: "Boyunca" },
        { word: "Experience", translation: "Deneyim" },
        { word: "Happen", translation: "Olmak, meydana gelmek" },
        { word: "Invite", translation: "Davet etmek" },
        { word: "Meet", translation: "Tanışmak, buluşmak" },
        { word: "Remember", translation: "Hatırlamak" },
        { word: "Forget", translation: "Unutmak" },
        { word: "Move", translation: "Hareket etmek, taşınmak" },
        { word: "Laugh", translation: "Gülmek" },
        { word: "Cry", translation: "Ağlamak" },
        { word: "Safe", translation: "Güvenli" },
        { word: "Dangerous", translation: "Tehlikeli" },
        { word: "Health", translation: "Sağlık" },
        { word: "Body", translation: "Vücut" },
        { word: "Mind", translation: "Zihin" },
        { word: "Feeling", translation: "Duygu" },
        { word: "Excited", translation: "Heyecanlı" },
        { word: "Tired", translation: "Yorgun" },
        { word: "Start", translation: "Başlamak" },
        { word: "Finish", translation: "Bitirmek" },
        { word: "Practice", translation: "Pratik yapmak" },
        { word: "Study", translation: "Çalışmak (ders)" },
        { word: "Learn", translation: "Öğrenmek" },
        { word: "Teach", translation: "Öğretmek" },
        { word: "Ask", translation: "Sormak" },
        { word: "Answer", translation: "Cevaplamak" },
        { word: "Help", translation: "Yardım etmek" },
        { word: "Need", translation: "İhtiyaç duymak" },
        { word: "Want", translation: "İstemek" },
        { word: "Like", translation: "Sevmek, beğenmek" },
        { word: "Hate", translation: "Nefret etmek" },
        { word: "Kitchen", translation: "Mutfak" },
        { word: "Bathroom", translation: "Banyo" },
        { word: "Garden", translation: "Bahçe" },
        { word: "Street", translation: "Cadde" },
        { word: "Village", translation: "Köy" },
        { word: "Airport", translation: "Havaalanı" },
        { word: "Station", translation: "İstasyon" },
        { word: "Bus", translation: "Otobüs" },
        { word: "Train", translation: "Tren" },
        { word: "Plane", translation: "Uçak" },
        { word: "Wait", translation: "Beklemek" },
        { word: "Hurry", translation: "Acele etmek" },
        { word: "Suggest", translation: "Önermek" },
        { word: "Decide", translation: "Karar vermek" },
        { word: "Plan", translation: "Planlamak" },
        { word: "Hope", translation: "Umut etmek" },
        { word: "Believe", translation: "İnanmak" },
        { word: "Show", translation: "Göstermek" },
        { word: "Wear", translation: "Giymek" },
        { word: "Wash", translation: "Yıkamak" },
        { word: "Clean", translation: "Temizlemek" },
        { word: "Dirty", translation: "Kirli" },
        { word: "Empty", translation: "Boş" },
        { word: "Full", translation: "Dolu" },
        { word: "Near", translation: "Yakın" },
        { word: "Far", translation: "Uzak" },
        { word: "Between", translation: "Arasında" },
        { word: "Next to", translation: "Yanında" },
        { word: "Opposite", translation: "Karşısında" },
        { word: "Middle", translation: "Orta" },
        { word: "Corner", translation: "Köşe" },
        { word: "Side", translation: "Yan" },
        { word: "Top", translation: "Tepe, üst" },
        { word: "Bottom", translation: "Dip, alt" },
        { word: "Inside", translation: "İçeride" },
        { word: "Outside", translation: "Dışarıda" },
        { word: "Throw", translation: "Atmak" },
        { word: "Catch", translation: "Yakalamak" },
        { word: "Win", translation: "Kazanmak" },
        { word: "Lose", translation: "Kaybetmek" },
        { word: "Sport", translation: "Spor" },
        { word: "Game", translation: "Oyun" },
        { word: "Film", translation: "Film" },
        { word: "Music", translation: "Müzik" }
    ],
    B1: [
        { word: "Achieve", translation: "Başarmak" },
        { word: "Concentrate", translation: "Odaklanmak" },
        { word: "Opportunity", translation: "Fırsat" },
        { word: "Consider", translation: "Düşünmek" },
        { word: "Involve", translation: "Dahil etmek" },
        { word: "Reliable", translation: "Güvenilir" },
        { word: "Variety", translation: "Çeşitlilik" },
        { word: "Essential", translation: "Temel, zorunlu" },
        { word: "Behavior", translation: "Davranış" },
        { word: "Complain", translation: "Şikayet etmek" },
        { word: "Advertise", translation: "Reklam yapmak" },
        { word: "Career", translation: "Kariyer" },
        { word: "Community", translation: "Topluluk" },
        { word: "Develop", translation: "Geliştirmek" },
        { word: "Efficient", translation: "Verimli" },
        { word: "Environment", translation: "Çevre" },
        { word: "Immediately", translation: "Hemen, derhal" },
        { word: "Improve", translation: "İyileştirmek" },
        { word: "Influence", translation: "Etkilemek" },
        { word: "Investment", translation: "Yatırım" },
        { word: "Judge", translation: "Yargılamak, yargıç" },
        { word: "Knowledge", translation: "Bilgi" },
        { word: "Manage", translation: "Yönetmek" },
        { word: "Measure", translation: "Ölçmek" },
        { word: "Necessary", translation: "Gerekli" },
        { word: "Perform", translation: "Sergilemek, icra etmek" },
        { word: "Quality", translation: "Kalite" },
        { word: "Relationship", translation: "İlişki" },
        { word: "Responsibility", translation: "Sorumluluk" },
        { word: "Satisfied", translation: "Memnun" },
        { word: "Skill", translation: "Beceri" },
        { word: "Solution", translation: "Çözüm" },
        { word: "Suggest", translation: "Teklif etmek, önermek" },
        { word: "Support", translation: "Desteklemek" },
        { word: "Target", translation: "Hedef" },
        { word: "Tolerate", translation: "Hoş görmek" },
        { word: "Unusual", translation: "Alışılmadık" },
        { word: "Value", translation: "Değer" },
        { word: "Witness", translation: "Şahit olmak" },
        { word: "Access", translation: "Erişim" },
        { word: "Approach", translation: "Yaklaşım" },
        { word: "Argument", translation: "Tartışma" },
        { word: "Attitude", translation: "Tutum" },
        { word: "Challenge", translation: "Meydan okuma" },
        { word: "Claim", translation: "İddia etmek" },
        { word: "Confused", translation: "Şaşkın, kafası karışık" },
        { word: "Create", translation: "Yaratmak" },
        { word: "Damage", translation: "Hasar vermek" },
        { word: "Demand", translation: "Talep etmek" },
        { word: "Effect", translation: "Etki" },
        { word: "Eventually", translation: "Eninde sonunda" },
        { word: "Exist", translation: "Var olmak" },
        { word: "Feature", translation: "Özellik" },
        { word: "Flexible", translation: "Esnek" },
        { word: "Generate", translation: "Üretmek" },
        { word: "Habit", translation: "Alışkanlık" },
        { word: "Identity", translation: "Kimlik" },
        { word: "Imagine", translation: "Hayal etmek" },
        { word: "Indicate", translation: "Göstermek, işaret etmek" },
        { word: "Legal", translation: "Yasal" },
        { word: "Limit", translation: "Sınırlamak" },
        { word: "Locate", translation: "Yerini belirlemek" },
        { word: "Mental", translation: "Zihinsel" },
        { word: "Mission", translation: "Görev" },
        { word: "Negative", translation: "Olumsuz" },
        { word: "Obtain", translation: "Elde etmek" },
        { word: "Official", translation: "Resmi" },
        { word: "Prevent", translation: "Önlemek" },
        { word: "Proceed", translation: "İlerlemek" },
        { word: "Purpose", translation: "Amaç" },
        { word: "Rarely", translation: "Nadiren" },
        { word: "Reflect", translation: "Yansıtmak" },
        { word: "Region", translation: "Bölge" },
        { word: "Register", translation: "Kayıt olmak" },
        { word: "Remove", translation: "Kaldırmak" },
        { word: "Source", translation: "Kaynak" },
        { word: "Spend", translation: "Harcamak (para/zaman)" },
        { word: "Standard", translation: "Standart" },
        { word: "Structure", translation: "Yapı" },
        { word: "Success", translation: "Başarı" },
        { word: "Technology", translation: "Teknoloji" },
        { word: "Temporary", translation: "Geçici" },
        { word: "Threat", translation: "Tehdit" },
        { word: "Topic", translation: "Konu" },
        { word: "Trend", translation: "Eğilim" },
        { word: "Unique", translation: "Eşsiz" },
        { word: "Universal", translation: "Evrensel" },
        { word: "Version", translation: "Sürüm" },
        { word: "Visible", translation: "Görünür" },
        { word: "Worry", translation: "Endişelenmek" },
        { word: "Active", translation: "Aktif" },
        { word: "Confirm", translation: "Onaylamak" },
        { word: "Initial", translation: "İlk, başlangıç" },
        { word: "Option", translation: "Seçenek" }
    ],
    B2: [
        { word: "Consequence", translation: "Sonuç, netice" },
        { word: "Demonstrate", translation: "Kanıtlamak, göstermek" },
        { word: "Eventually", translation: "Eninde sonunda" },
        { word: "Impact", translation: "Etki" },
        { word: "Maintain", translation: "Sürdürmek" },
        { word: "Perspective", translation: "Bakış açısı" },
        { word: "Significant", translation: "Önemli, kayda değer" },
        { word: "Undergo", translation: "Geçirmek, maruz kalmak" },
        { word: "Acquire", translation: "Edinmek" },
        { word: "Coherent", translation: "Tutarlı" },
        { word: "Allocate", translation: "Tahsis etmek" },
        { word: "Alternative", translation: "Alternatif" },
        { word: "Aspect", translation: "Yön, bakış açısı" },
        { word: "Compensate", translation: "Tazmin etmek" },
        { word: "Component", translation: "Bileşen" },
        { word: "Contribute", translation: "Katkıda bulunmak" },
        { word: "Criteria", translation: "Kriterler" },
        { word: "Crucial", translation: "Çok önemli" },
        { word: "Deduce", translation: "Sonuç çıkarmak" },
        { word: "Define", translation: "Tanımlamak" },
        { word: "Dispose", translation: "Elden çıkarmak" },
        { word: "Distort", translation: "Çarpıtmak" },
        { word: "Dynamic", translation: "Dinamik" },
        { word: "Emerge", translation: "Ortaya çıkmak" },
        { word: "Equivalent", translation: "Eşdeğer" },
        { word: "Estimate", translation: "Tahmin etmek" },
        { word: "Exceed", translation: "Aşmak, geçmek" },
        { word: "Expose", translation: "Maruz bırakmak" },
        { word: "Fluctuate", translation: "Dalgalanmak" },
        { word: "Guarantee", translation: "Garanti etmek" },
        { word: "Hierarchy", translation: "Hiyerarşi" },
        { word: "Imply", translation: "İma etmek" },
        { word: "Incentive", translation: "Teşvik" },
        { word: "Integrate", translation: "Bütünleştirmek" },
        { word: "Interpret", translation: "Yorumlamak" },
        { word: "Invalid", translation: "Geçersiz" },
        { word: "Justify", translation: "Haklı çıkarmak" },
        { word: "Legend", translation: "Efsane" },
        { word: "Mechanism", translation: "Mekanizma" },
        { word: "Modify", translation: "Değiştirmek, tadil etmek" },
        { word: "Outcome", translation: "Sonuç" },
        { word: "Overall", translation: "Genel olarak" },
        { word: "Predict", translation: "Tahmin etmek" },
        { word: "Prioritize", translation: "Öncelik vermek" },
        { word: "Prohibit", translation: "Yasaklamak" },
        { word: "Publish", translation: "Yayınlamak" },
        { word: "Relevant", translation: "İlgili" },
        { word: "Resolve", translation: "Çözmek (sorun)" },
        { word: "Restrict", translation: "Kısıtlamak" },
        { word: "Revenue", translation: "Gelir" },
        { word: "Sequence", translation: "Sıra, dizi" },
        { word: "Simplify", translation: "Basitleştirmek" },
        { word: "Specify", translation: "Belirtmek" },
        { word: "Substitute", translation: "Yerine geçmek, vekil" },
        { word: "Suspend", translation: "Askıya almak" },
        { word: "Sustain", translation: "Sürdürmek, devam ettirmek" },
        { word: "Transform", translation: "Dönüştürmek" },
        { word: "Transmit", translation: "İletmek" },
        { word: "Underlying", translation: "Altta yatan" },
        { word: "Validate", translation: "Doğrulamak" },
        { word: "Voluntary", translation: "Gönüllü" },
        { word: "Vulnerable", translation: "Savunmasız" },
        { word: "Widespread", translation: "Yaygın" },
        { word: "Abstract", translation: "Soyut" },
        { word: "Acknowledge", translation: "Kabul etmek, onaylamak" },
        { word: "Consist", translation: "Oluşmak" },
        { word: "Convene", translation: "Toplanmak" },
        { word: "Crucial", translation: "Hayatı öneme sahip" },
        { word: "Depict", translation: "Tasvir etmek" },
        { word: "Diminish", translation: "Azaltmak" },
        { word: "Erode", translation: "Aşındırmak" },
        { word: "Evoke", translation: "Çağrıştırmak" },
        { word: "Inquire", translation: "Soruşturmak" },
        { word: "Intrinsic", translation: "Doğal, özgün" },
        { word: "Paradox", translation: "Paradoks" },
        { word: "Prompt", translation: "Harekete geçirmek" },
        { word: "Scrutinize", translation: "İncelemek" },
        { word: "Subtle", translation: "İnce, zor fark edilen" },
        { word: "Surpass", translation: "Aşmak, geçmek" },
        { word: "Tentative", translation: "Geçici, kesin olmayan" },
        { word: "Ultimate", translation: "Nihai, son" },
        { word: "Unprecedented", translation: "Eşi benzeri görülmemiş" },
        { word: "Vary", translation: "Değişmek" },
        { word: "Vigilant", translation: "Teyakkuzda, dikkatli" },
        { word: "Aptitude", translation: "Yetenek" },
        { word: "Coercion", translation: "Zorlama, cebir" },
        { word: "Discrepancy", translation: "Tutarsızlık" }
    ],
    C1: [
        { word: "Elaborate", translation: "Detaylandırmak" },
        { word: "Inherent", translation: "Doğuştan, doğasında olan" },
        { word: "Juxtapose", translation: "Yan yana koymak" },
        { word: "Mitigate", translation: "Yumuşatmak, hafifletmek" },
        { word: "Paradigm", translation: "Model, örnek" },
        { word: "Prevalent", translation: "Yaygın, baskın" },
        { word: "Ubiquitous", translation: "Her yerde bulunan" },
        { word: "Viable", translation: "Uygulanabilir, yaşayabilir" },
        { word: "Cognizant", translation: "Farkında olan" },
        { word: "Disseminate", translation: "Yayınlamak, yaymak" },
        { word: "Abridge", translation: "Kısaltmak, özetlemek" },
        { word: "Ambiguous", translation: "Belirsiz, muğlak" },
        { word: "Ascertain", translation: "Belirlemek, kesinleştirmek" },
        { word: "Capricious", translation: "Kaprisli, değişken" },
        { word: "Circumvent", translation: "Atlatmak, yanından dolaşmak" },
        { word: "Concur", translation: "Aynı fikirde olmak" },
        { word: "Corroborate", translation: "Doğrulamak, teyit etmek" },
        { word: "Deplore", translation: "Şiddetle kınamak" },
        { word: "Derive", translation: "Türetmek, elde etmek" },
        { word: "Disparity", translation: "Eşitsizlik, farklılık" },
        { word: "Efficacy", translation: "Etkililik, verim" },
        { word: "Embody", translation: "Temsil etmek, somutlaştırmak" },
        { word: "Encompass", translation: "Kapsamak" },
        { word: "Equivocal", translation: "İki anlamlı" },
        { word: "Exacerbate", translation: "Kötüleştirmek" },
        { word: "Expedient", translation: "Uygun, faydalı" },
        { word: "Foresight", translation: "Öngörü" },
        { word: "Gratuitous", translation: "Gereksiz, karşılıksız" },
        { word: "Hinder", translation: "Engellemek" },
        { word: "Immutable", translation: "Değişmez" },
        { word: "Inadvertent", translation: "İstemsiz, dikkatsiz" },
        { word: "Incorrigible", translation: "Islah olmaz" },
        { word: "Inference", translation: "Çıkarım" },
        { word: "Instigate", translation: "Kışkırtmak, başlatmak" },
        { word: "Intractable", translation: "İnatçı, zorlu" },
        { word: "Irrevocable", translation: "Geri alınamaz" },
        { word: "Lament", translation: "Yas tutmak, sızlanmak" },
        { word: "Liaison", translation: "İletişim, irtibat" },
        { word: "Mandate", translation: "Görev, yetki" },
        { word: "Meticulous", translation: "Titiz" },
        { word: "Nominal", translation: "İsmen, göstermelik" },
        { word: "Oblivious", translation: "Farkında olmayan" },
        { word: "Onerous", translation: "Zahmetli, külfetli" },
        { word: "Ostracize", translation: "Dışlamak" },
        { word: "Perpetuate", translation: "Sürdürmek, devam ettirmek" },
        { word: "Pervasive", translation: "Yaygın, her yere sinmiş" },
        { word: "Precarious", translation: "Tehlikeli, istikrarsız" },
        { word: "Proponent", translation: "Savunan, destekçi" },
        { word: "Quell", translation: "Bastırmak, yatıştırmak" },
        { word: "Rancor", translation: "Kin, nefret" },
        { word: "Reciprocate", translation: "Karşılık vermek" },
        { word: "Redundant", translation: "Gereksiz, fazla" },
        { word: "Reiterate", translation: "Tekrarlamak" },
        { word: "Sanction", translation: "Yaptırım" },
        { word: "Scrutiny", translation: "Yakın inceleme" },
        { word: "Sporadic", translation: "Düzensiz, ara sıra" },
        { word: "Substantiate", translation: "Kanıtlamak, desteklemek" },
        { word: "Superfluous", translation: "Gereksiz, fazlalık" },
        { word: "Synthesize", translation: "Sentezlemek" },
        { word: "Tenuous", translation: "İnce, zayıf" },
        { word: "Transcendent", translation: "Aşkın, üstün" },
        { word: "Undermine", translation: "Baltalamak, zayıflatmak" },
        { word: "Unilateral", translation: "Tek taraflı" },
        { word: "Unwarranted", translation: "Gerekçesiz" },
        { word: "Vacillate", translation: "Tereddüt etmek, bocalamak" },
        { word: "Venerate", translation: "Saygı duymak" },
        { word: "Vex", translation: "Canını sıkmak, kızdırmak" },
        { word: "Vindictive", translation: "Kindar" },
        { word: "Wistful", translation: "Özlem dolu, hüzünlü" },
        { word: "Zealous", translation: "Şevkli, gayretli" },
        { word: "Acumen", translation: "Zeka, keskin görüş" },
        { word: "Austerity", translation: "Sertlik, tutumluluk" },
        { word: "Clandestine", translation: "Gizli, saklı" },
        { word: "Deference", translation: "Saygı" },
        { word: "Ephemeral", translation: "Kısa ömürlü" },
        { word: "Fortuitous", translation: "Şans eseri" },
        { word: "Immutable", translation: "Değişmez" },
        { word: "Insolent", translation: "Küçümseyen, saygısız" },
        { word: "Nuance", translation: "Nüans, ince ayrıntı" },
        { word: "Palliative", translation: "Hafifletici" },
        { word: "Quiescent", translation: "Hareketsiz, durgun" }
    ],
    C2: [
        { word: "Epitome", translation: "Mükemmel örnek" },
        { word: "Ineffable", translation: "Anlatılmaz, dile gelmez" },
        { word: "Pernicious", translation: "Zararlı, kötü niyetli" },
        { word: "Quixotic", translation: "Hayalperest, pratik olmayan" },
        { word: "Salient", translation: "Göze çarpan, dikkat çekici" },
        { word: "Serendipity", translation: "Şans eseri güzel buluş" },
        { word: "Truncate", translation: "Kısaltmak, kesmek" },
        { word: "Vituperate", translation: "Ağır eleştiri yapmak" },
        { word: "Lugubrious", translation: "Hüzünlü, kederli" },
        { word: "Mellifluous", translation: "Tatlı sesli, ahenkli" },
        { word: "Abstruse", translation: "Anlaşılması güç" },
        { word: "Adumbrate", translation: "Ana hatlarını çizmek" },
        { word: "Alacrity", translation: "İsteklilik, şevk" },
        { word: "Anathema", translation: "Lanet, nefret edilen şey" },
        { word: "Arcane", translation: "Gizemli, bilinmeyen" },
        { word: "Bilk", translation: "Dolandırmak" },
        { word: "Cajole", translation: "Tatlı sözle kandırmak" },
        { word: "Calumny", translation: "İftira" },
        { word: "Capitulate", translation: "Teslim olmak" },
        { word: "Chicanery", translation: "Hile, dalavere" },
        { word: "Contrite", translation: "Pişman, nedametli" },
        { word: "Dichotomy", translation: "İkilik, karşıtlık" },
        { word: "Disparate", translation: "Farklı, alakasız" },
        { word: "Egregious", translation: "Fevkalade kötü" },
        { word: "Elicit", translation: "Ortaya çıkarmak" },
        { word: "Exigency", translation: "Acil ihtiyaç" },
        { word: "Fastidious", translation: "Titiz, zor beğenen" },
        { word: "Fatuous", translation: "Aptalca, beyhude" },
        { word: "Feckless", translation: "Beceriksiz, sorumsuz" },
        { word: "Fecund", translation: "Bereketli, üretken" },
        { word: "Garrulous", translation: "Çok konuşan" },
        { word: "Hegemony", translation: "Egemenlik, liderlik" },
        { word: "Impecunious", translation: "Parası olmayan, fakir" },
        { word: "Inchoate", translation: "Başlangıç aşamasında, eksik" },
        { word: "Inexorable", translation: "Kaçınılmaz" },
        { word: "Inimical", translation: "Düşmanca" },
        { word: "Insidious", translation: "Sinsi" },
        { word: "Intrepid", translation: "Korkusuz" },
        { word: "Languid", translation: "Halsiz, uyuşuk" },
        { word: "Malediction", translation: "Lanet, beddua" },
        { word: "Mendacious", translation: "Yalancı" },
        { word: "Nefarious", translation: "Kötü şöhretli" },
        { word: "Obfuscate", translation: "Kafasını karıştırmak" },
        { word: "Obsequious", translation: "Dalkavuk" },
        { word: "Panacea", translation: "Her derde deva" },
        { word: "Pedantic", translation: "Bilgiçlik taslayan" },
        { word: "Perfunctory", translation: "Gelişigüzel, özensiz" },
        { word: "Placate", translation: "Yatıştırmak" },
        { word: "Poignant", translation: "Dokunaklı, acı" },
        { word: "Profligate", translation: "Savurgan" },
        { word: "Pugnacious", translation: "Kavgacı" },
        { word: "Remiss", translation: "İhmalkar" },
        { word: "Repudiate", translation: "Reddetmek, tanımamak" },
        { word: "Reticent", translation: "Sessiz, çekingen" },
        { word: "Ruminate", translation: "Derin düşünmek" },
        { word: "Sycophant", translation: "Dalkavuk" },
        { word: "Tacit", translation: "Zımni, örtük" },
        { word: "Tautological", translation: "Gereksiz tekrarlayıcı" },
        { word: "Temerity", translation: "Cüret, pervasızlık" },
        { word: "Tractability", translation: "Uysallık" },
        { word: "Truculent", translation: "Sert, kaba" },
        { word: "Vacuous", translation: "Anlamsız, boş" },
        { word: "Vilify", translation: "Kötülemek" },
        { word: "Wry", translation: "Alaycı, çarpık" },
        { word: "Zenith", translation: "Zirve" },
        { word: "Ameliorate", translation: "İyileştirmek" },
        { word: "Ephemeral", translation: "Kısa ömürlü" },
        { word: "Exonerate", translation: "Aklamak" },
        { word: "Impute", translation: "Yüklemek, atfetmek" },
        { word: "Injunction", translation: "Emir, yasaklama" },
        { word: "Insular", translation: "Dar görüşlü" },
        { word: "Lackadaisical", translation: "Umursamaz" },
        { word: "Maverick", translation: "Başkasına uymayan" },
        { word: "Plethora", translation: "Aşırı bolluk" },
        { word: "Subjugate", translation: "Boyun eğdirmek" },
        { word: "Surreptitious", translation: "Gizlice yapılan" },
        { word: "Turpitude", translation: "Ahlaki düşkünlük" },
        { word: "Vicissitude", translation: "Değişiklik, iniş çıkış" }
    ]
};